[package]
name = "batt_low"
version = "0.1.0"
edition = "2024"
authors = ["ekahPruthvi <ekahpdp@gmail.com>"]
description = "battery error window"
license = "GPL-3.0"

[dependencies]
gtk4 = "0.9.7"
gtk4-layer-shell = "0.5.0"
rand = "0.9.1"
